services:
  web-notification:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web-notification
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
    - web-notification-network

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      PGDATA: /data/postgres

    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  web-notification-network:
    driver: bridge

volumes:
  db: