spring:
  application:
    name: web-notification

  datasource:
    url: jdbc:postgresql://localhost:5432/we_notification
    driver-class-name: org.postgresql.Driver
    username: postgre
    password: postgre
    hikari:
      maximum-pool-size: 20           # Tune based on DB capacity
      minimum-idle: 5
      idle-timeout: 30000             # 30 seconds
      max-lifetime: 1800000           # 30 minutes
      connection-timeout: 30000       # 30 seconds
      validation-timeout: 5000        # 5 seconds
      leak-detection-threshold: 2000  # 2 seconds (Optional: good for debugging connection leaks)
      pool-name: HikariCP

# create and drop table, good for testing, production set to none or comment it
  jpa:
    hibernate:
      ddl-auto: update                  # Never use 'create' or 'update' in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 30              # Batch inserts/updates
        order_inserts: true
        order_updates: true
        generate_statistics: false
    show-sql: true                   # Disable in prod
    open-in-view: false
    repositories:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health, metrics

server:
  port: ${SERVER_PORT:8080}
  tomcat:
    max-connections: 10000
    threads:
      max: 2000


websocket:
  allowed-origins:
    - http://localhost:8080
    - http://127.0.0.1:5500
    - http://myapp.com